#!/bin/sh

# Prints the current brightness

case $BLOCK_BUTTON in
        4) brightnessctl set 10+% ;;
        5) brightnessctl set 10-% ;;
        3) notify-send "🌒 Brightness module" "\- Shows brightness 🌒.
- Scroll to change." ;;
        6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

brightness=`printf "%.0f\n" $(brightnessctl get)//1000`

if [ "$brightness" -gt "70" ]; then
        icon="🌝"
elif [ "$brightness" -gt "50" ]; then
        icon="🌔"
elif [ "$brightness" -lt "30" ]; then
        icon="🌒"
else
        icon="🌓"
fi

printf "%s %s%%\\n" "$icon" "$brightness"
